# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [31]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os


# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [32]:
weather= "../Output/weather.csv"
cities_df = pd.read_csv(weather)
cities_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Avarua,-21.2078,-159.7750,23.03,100,6,1.03,CK,1650039761
1,Saint George,37.1041,-113.5841,17.46,19,0,1.54,US,1650039745
2,Saldanha,-33.0117,17.9442,20.03,55,0,10.76,ZA,1650039648
3,Port Alfred,-33.5906,26.8910,16.21,81,99,1.34,ZA,1650039750
4,Korla,41.7597,86.1469,15.11,13,0,4.12,CN,1650039939

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [33]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [34]:
#Store 'Lat' and 'Lng' into  locations 
locations = cities_df[["Lat", "Lng"]].astype(float)
humidity_perc=cities_df["Humidity"].astype(float)
humidity_perc

0      100.0
1       19.0
2       55.0
3       81.0
4       13.0
       ...
562     47.0
563     66.0
564     96.0
565     25.0
566     47.0
Name: Humidity, Length: 567, dtype: float64

In [36]:
# Create a Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_perc, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [83]:
# Narrowing down to the ideal weather locations
my_sites=cities_df.loc[(cities_df['Max Temp']<=25)&(cities_df['Country']=="US")&(cities_df['Max Temp']<=25)&(cities_df['Max Temp']>=20)&(cities_df['Wind Speed']<=5)]
my_sites

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
6,Hilo,19.7297,-155.0900,23.49,88,75,3.09,US,1650039764
46,Kahului,20.8947,-156.4700,22.69,75,20,4.12,US,1650039783
80,Lebanon,36.2081,-86.2911,22.03,25,0,3.09,US,1650039924
108,Mayo,38.8876,-76.5119,21.42,28,0,1.79,US,1650039921
257,Apache Junction,33.4151,-111.5496,24.01,13,0,4.63,US,1650039869
370,Lahaina,20.8783,-156.6825,22.67,84,48,4.42,US,1650040072
374,Morgan City,29.6994,-91.2068,23.33,88,100,4.12,US,1650040074
494,Old Bridge,40.4148,-74.3654,20.03,24,5,1.79,US,1650040120
533,Sulphur Springs,33.1385,-95.6011,21.62,73,100,3.60,US,1650040135

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [84]:
hotel_df=my_sites.copy()
hotel_df["Hotel Name"] = ""
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
6,Hilo,19.7297,-155.0900,23.49,88,75,3.09,US,1650039764,
46,Kahului,20.8947,-156.4700,22.69,75,20,4.12,US,1650039783,
80,Lebanon,36.2081,-86.2911,22.03,25,0,3.09,US,1650039924,
108,Mayo,38.8876,-76.5119,21.42,28,0,1.79,US,1650039921,
257,Apache Junction,33.4151,-111.5496,24.01,13,0,4.63,US,1650039869,
370,Lahaina,20.8783,-156.6825,22.67,84,48,4.42,US,1650040072,
374,Morgan City,29.6994,-91.2068,23.33,88,100,4.12,US,1650040074,
494,Old Bridge,40.4148,-74.3654,20.03,24,5,1.79,US,1650040120,
533,Sulphur Springs,33.1385,-95.6011,21.62,73,100,3.60,US,1650040135,

In [88]:
# create a params dict that will be updated with new city each iteration
params = {"key": g_key,"type":"lodging","radius":5000}

In [93]:
# Loop through the hotel_df and run a lat/long search for each city
for index, row in hotel_df.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    city = row['City']
    country=row['Country']
    #state = row['State']

    # update address key value
    params['location']= f'{row["Lat"]},{row["Lng"]}'

    # make request
    cities_lat_lng = requests.get(base_url, params=params)
    
    # print the cities_lat_lng url, avoid doing for public github repos in order to avoid exposing key
    #print(cities_lat_lng.url)
    
    # convert to json
    cities_lat_lng = cities_lat_lng.json()
    print(cities_lat_lng["results"][0]["name"])
    hotel_data=cities_lat_lng["results"][0]["name"]
    hotel_df.at[index,'Hotel Name']=hotel_data

Hilo Hawaiian Hotel
Maui Seaside Hotel
Hampton Inn & Suites Lebanon
Resorts Resource Group International
Motel 6 Apache Junction, AZ
Lahaina Shores Beach Resort
Hampton Inn & Suites Morgan City
SureStay Hotel By Best Western East Brunswick
Clarion Pointe Sulphur Springs

In [94]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [95]:
# Add marker layer ontop of heat map
markers=gmaps.marker_layer(locations,info_box_content=hotel_info)

fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [96]:
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
6,Hilo,19.7297,-155.0900,23.49,88,75,3.09,US,1650039764,Hilo Hawaiian Hotel
46,Kahului,20.8947,-156.4700,22.69,75,20,4.12,US,1650039783,Maui Seaside Hotel
80,Lebanon,36.2081,-86.2911,22.03,25,0,3.09,US,1650039924,Hampton Inn & Suites Lebanon
108,Mayo,38.8876,-76.5119,21.42,28,0,1.79,US,1650039921,Resorts Resource Group International
257,Apache Junction,33.4151,-111.5496,24.01,13,0,4.63,US,1650039869,"Motel 6 Apache Junction, AZ"
370,Lahaina,20.8783,-156.6825,22.67,84,48,4.42,US,1650040072,Lahaina Shores Beach Resort
374,Morgan City,29.6994,-91.2068,23.33,88,100,4.12,US,1650040074,Hampton Inn & Suites Morgan City
494,Old Bridge,40.4148,-74.3654,20.03,24,5,1.79,US,1650040120,SureStay Hotel By Best Western East Brunswick
533,Sulphur Springs,33.1385,-95.6011,21.62,73,100,3.60,US,1650040135,Clarion Pointe Sulphur Springs